### Step 0: What You Are Going to Build

You will:

- Load a dataset

- Split data

- Apply Feature Scaling

- Train a model

- Apply Cross Validation

- Compare results

### Step 1: Import libraries

In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_breast_cancer

### Step 2: Load DATASET

In [ ]:
data = load_breast_cancer()

X = data.data      # features
y = data.target    # labels
"""🧠 What is Happening
X → input features (like size, texture, etc.)
y → output (0 = malignant, 1 = benign)"""

'🧠 What is Happening\nX → input features (like size, texture, etc.)\ny → output (0 = malignant, 1 = benign)'

### Step 3: Train-Test Split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

 IMPORTANT RULE (REMEMBER FOREVER)

👉 Never scale before splitting

Correct order:
✔ Split → then scale

### ⚖️ Step 4: Apply Feature Scaling
🔹 Option 1: Standardization

In [ ]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

"""What happens here:
fit() → Learns parameters from training data
For example:
Mean (in StandardScaler)
Min & Max (in MinMaxScaler)
transform() → Applies scaling using those learned values
👉 So fit_transform() = learn + apply"""

X_test_scaled = scaler.transform(X_test)
"""What happens here:
ONLY transform() is used
It uses the same parameters learned from training data
👉 No learning from test data ❌"""

'What happens here:\nONLY transform() is used\nIt uses the same parameters learned from training data\n👉 No learning from test data ❌'

🔍 What’s Happening
fit_transform() (only on training data)

👉 Learns:

Mean

Standard deviation

👉 Then transforms data

transform() (on test data)

👉 Uses same mean & std

👉 Prevents data leakage

🔹 Option 2: Normalization (Try separately)

scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

### 🤖 Step 5: Train Model

In [ ]:
model = LogisticRegression(max_iter=5000)
model.fit(X_train_scaled, y_train)

"""🔍 Explanation
max_iter=1000 → ensures convergence
fit() → trains model"""

'🔍 Explanation\nmax_iter=1000 → ensures convergence\nfit() → trains model'

### 🎯 Step 6: Evaluate (Simple Accuracy)


In [ ]:
accuracy = model.score(X_test_scaled, y_test)
print("Test Accuracy:", accuracy)

Test Accuracy: 0.9736842105263158


### 🔁 Step 7: Apply Cross Validation

❗ Important:

Cross validation should be done on full dataset (X, y)

In [ ]:
scores = cross_val_score(
    model, X_train_scaled, y_train, cv=5
)

🔍 Explanation

model → algorithm

X_train_scaled → input

y_train → output

cv=5 → 5-fold cross validation

### 📊 Step 8: Print Results

In [ ]:
print("Cross Validation Scores:", scores)
print("Average CV Score:", scores.mean())

Cross Validation Scores: [0.97802198 0.96703297 1.         0.97802198 0.94505495]
Average CV Score: 0.9736263736263737


🧠 What You Get

Example:

[0.95, 0.96, 0.94, 0.97, 0.95]

👉 Each fold accuracy

Final:

👉 Average = real performance

### ⚖️ Step 9: Compare Scaling vs No Scaling

In [ ]:
scores_no_scaling = cross_val_score(
    model, X_train, y_train, cv=5
)

print("Without Scaling:", scores_no_scaling.mean())
print("With Scaling:", scores.mean())

Without Scaling: 0.9538461538461538
With Scaling: 0.9736263736263737


### Difference between fit_transform() and transform() (with reason):

fit_transform() is used on the training data. It first learns the parameters of the data, such as mean and standard deviation (in the case of scaling), and then transforms the data using those learned values.

transform() is used on the test data. It does not learn anything new; instead, it uses the same parameters that were calculated from the training data to transform the test data.

The reason for this is to prevent data leakage. If we use fit_transform() on the test data, the model would learn information from the test set, which should remain unseen during training. Therefore, we use fit_transform() only on training data and transform() on test data to ensure a fair and unbiased evaluation of the model.

In [ ]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# Sample data with different scales
data = np.array([
    [25, 50000],    # Age 25, Salary 50k
    [30, 75000],    # Age 30, Salary 75k
    [45, 120000],   # Age 45, Salary 120k
    [35, 90000]     # Age 35, Salary 90k
])

scaler = MinMaxScaler(feature_range=(0, 1))  # Default range
data_scaled = scaler.fit_transform(data)

print("Original Data:")
print(data)
print("\nFeature ranges:")
print(f"Age range: {data[:,0].min()} - {data[:,0].max()}")
print(f"Salary range: ${data[:,1].min()} - ${data[:,1].max()}")

print("\nScaled Data (0-1):")
print(data_scaled)
print("\nScaled ranges:")
print(f"Age scaled: {data_scaled[:,0].min()} - {data_scaled[:,0].max()}")
print(f"Salary scaled: {data_scaled[:,1].min()} - {data_scaled[:,1].max()}")

# Output:
# Original Data:
# [[    25  50000]
#  [    30  75000]
#  [    45 120000]
#  [    35  90000]]

# Scaled Data (0-1):
# [[0.   0.   ]
#  [0.25 0.357]
#  [1.   1.   ]
#  [0.5  0.571]]

Original Data:
[[    25  50000]
 [    30  75000]
 [    45 120000]
 [    35  90000]]

Feature ranges:
Age range: 25 - 45
Salary range: $50000 - $120000

Scaled Data (0-1):
[[0.         0.        ]
 [0.25       0.35714286]
 [1.         1.        ]
 [0.5        0.57142857]]

Scaled ranges:
Age scaled: 0.0 - 1.0
Salary scaled: 0.0 - 0.9999999999999999


In [ ]:
from sklearn.preprocessing import StandardScaler
import numpy as np

# Same data as before
data = np.array([
    [25, 50000],
    [30, 75000],
    [45, 120000],
    [35, 90000]
])

scaler = StandardScaler()
data_scaled = scaler.fit_transform(data)

print("Original Data:")
print(data)
print(f"\nOriginal Mean: Age={data[:,0].mean():.1f}, Salary=${data[:,1].mean():.0f}")
print(f"Original Std: Age={data[:,0].std():.1f}, Salary=${data[:,1].std():.0f}")

print("\nScaled Data (Mean=0, Std=1):")
print(data_scaled)
print(f"\nScaled Mean: Age={data_scaled[:,0].mean():.2f}, Salary={data_scaled[:,1].mean():.2f}")
print(f"Scaled Std: Age={data_scaled[:,0].std():.2f}, Salary={data_scaled[:,1].std():.2f}")

# Output:
# Original Mean: Age=33.8, Salary=$83750
# Original Std: Age=7.4, Salary=$26836

# Scaled Mean: Age=-0.00, Salary=0.00
# Scaled Std: Age=1.00, Salary=1.00

Original Data:
[[    25  50000]
 [    30  75000]
 [    45 120000]
 [    35  90000]]

Original Mean: Age=33.8, Salary=$83750
Original Std: Age=7.4, Salary=$25341

Scaled Data (Mean=0, Std=1):
[[-1.18321596 -1.33181178]
 [-0.50709255 -0.34528454]
 [ 1.52127766  1.43046451]
 [ 0.16903085  0.24663181]]

Scaled Mean: Age=0.00, Salary=0.00
Scaled Std: Age=1.00, Salary=1.00


In [ ]:
print("""
Original Data Distribution:
    |
    |    *
    |   * *
    |  *   *
    | *     *
    |*       *
    +----------------
        10    50

After MinMaxScaler [0,1]:
    |
    |    *
    |   * *
    |  *   *
    | *     *
    |*       *
    +----------------
        0     1

After StandardScaler (μ=0, σ=1):
    |
    |    *
    |   * *
    |  *   *
    | *     *
    |*       *
    +----------------
       -2     2
""")


Original Data Distribution:
    |
    |    *
    |   * *
    |  *   *
    | *     *
    |*       *
    +----------------
        10    50

After MinMaxScaler [0,1]:
    |
    |    *
    |   * *
    |  *   *
    | *     *
    |*       *
    +----------------
        0     1

After StandardScaler (μ=0, σ=1):
    |
    |    *
    |   * *
    |  *   *
    | *     *
    |*       *
    +----------------
       -2     2



In [ ]:
print("""
                        START
                      ↓
            Is algorithm tree-based?
            (DT, RF, XGBoost)
                    ↓
            YES → NO SCALING NEEDED
                    ↓
                    NO
                    ↓
            Does data have outliers?
                    ↓
            YES → Use RobustScaler or
                  StandardScaler
                    ↓
                    NO
                    ↓
            Is bounded range [0,1] needed?
            (NN with sigmoid, image pixels)
                    ↓
            YES → Use MinMaxScaler
                    ↓
                    NO
                    ↓
            USE StandardScaler (default choice!)
""")


                        START
                      ↓
            Is algorithm tree-based?
            (DT, RF, XGBoost)
                    ↓
            YES → NO SCALING NEEDED
                    ↓
                    NO
                    ↓
            Does data have outliers?
                    ↓
            YES → Use RobustScaler or
                  StandardScaler
                    ↓
                    NO
                    ↓
            Is bounded range [0,1] needed?
            (NN with sigmoid, image pixels)
                    ↓
            YES → Use MinMaxScaler
                    ↓
                    NO
                    ↓
            USE StandardScaler (default choice!)



In [ ]:
print("""
# Label Encoding

Concept: Convert categories to integers (0, 1, 2, ...)
Best for: Ordinal data (ranked categories)

## Example:
Original: ['Red', 'Blue', 'Green', 'Red', 'Blue']
Result:   [2, 0, 1, 2, 0]
Mapping:  {'Blue': 0, 'Green': 1, 'Red': 2}

## Workflow:
                    
    ['Low', 'Medium', 'High', 'Medium']
                    │
                    ▼
    ┌───────────────────────────────┐
    │  FIT (Learn)                  │
    │  • Find unique values         │
    │  • Assign integers alphabetically │
    │                               │
    │  'High'  → 0                  │
    │  'Low'   → 1                  │
    │  'Medium'→ 2                  │
    └───────────────────────────────┘
                    │
                    ▼
    ┌───────────────────────────────┐
    │  TRANSFORM (Convert)          │
    │                               │
    │  'Low'    → 1                 │
    │  'Medium' → 2                 │
    │  'High'   → 0                 │
    │  'Medium' → 2                 │
    └───────────────────────────────┘
                    │
                    ▼
              [1, 2, 0, 2]

⚠️ Caution: Don't use for nominal data (colors, countries)
   Models may infer false ordering (0 < 1 < 2)
""")


# Label Encoding

Concept: Convert categories to integers (0, 1, 2, ...)
Best for: Ordinal data (ranked categories)

## Example:
Original: ['Red', 'Blue', 'Green', 'Red', 'Blue']
Result:   [2, 0, 1, 2, 0]
Mapping:  {'Blue': 0, 'Green': 1, 'Red': 2}

## Workflow:

    ['Low', 'Medium', 'High', 'Medium']
                    │
                    ▼
    ┌───────────────────────────────┐
    │  FIT (Learn)                  │
    │  • Find unique values         │
    │  • Assign integers alphabetically │
    │                               │
    │  'High'  → 0                  │
    │  'Low'   → 1                  │
    │  'Medium'→ 2                  │
    └───────────────────────────────┘
                    │
                    ▼
    ┌───────────────────────────────┐
    │  TRANSFORM (Convert)          │
    │                               │
    │  'Low'    → 1                 │
    │  'Medium' → 2                 │
    │  'High'   → 0                 │
    │  'Medium' → 2              

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Example 1: Ordinal data (Good use case)
education = ['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master']
le_edu = LabelEncoder()
education_encoded = le_edu.fit_transform(education)

print("Original:", education)
print("Encoded:", education_encoded)
print("Mapping:", dict(zip(le_edu.classes_, range(len(le_edu.classes_)))))

# Output:
# Original: ['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master']
# Encoded: [0, 1, 2, 0, 1]
# Mapping: {'Bachelor': 0, 'Master': 1, 'PhD': 2}

Original: ['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master']
Encoded: [0 1 2 0 1]
Mapping: {np.str_('Bachelor'): 0, np.str_('Master'): 1, np.str_('PhD'): 2}


In [ ]:
print("""
# 1.2 OneHotEncoder

## 📖 Definition
Creates binary columns for each category. Each column indicates presence (1) or absence (0) of that category.

## 🎯 When to Use
• Nominal data (no natural order)
• Features (X) for linear models (Logistic Regression, SVM, Neural Networks)

## Visual Representation

Original:    Color
            ┌─────┐
            │ Red │
            │ Blue│
            │Green│
            └─────┘

OneHotEncode ↓

        Red  Blue  Green
        ┌────┬─────┬─────┐
        │ 1  │ 0   │ 0   │  (Red)
        │ 0  │ 1   │ 0   │  (Blue)
        │ 0  │ 0   │ 1   │  (Green)
        └────┴─────┴─────┘

## 🔄 Workflow Diagram

┌──────────────────┐
│ Original Data    │  ['Red', 'Blue', 'Green', 'Blue']
└────────┬─────────┘
         ↓
┌──────────────────┐
│ Identify Unique  │  Categories: Red, Blue, Green
│ Categories       │  (n = 3 categories)
└────────┬─────────┘
         ↓
┌──────────────────┐
│ Create Binary    │  Create 3 new columns
│ Columns          │  [is_Red, is_Blue, is_Green]
└────────┬─────────┘
         ↓
┌──────────────────┐
│ Fill Values      │  Red    → [1, 0, 0]
│                  │  Blue   → [0, 1, 0]
│                  │  Green  → [0, 0, 1]
└──────────────────┘

## 📊 Mathematical Representation

For category k out of m total categories:

OneHot(xᵢ) = [I(xᵢ=c₁), I(xᵢ=c₂), ..., I(xᵢ=cₘ)]

Where I(condition) = 1 if condition is True, else 0

Example with 3 categories:
• Red:   [1, 0, 0]
• Blue:  [0, 1, 0]
• Green: [0, 0, 1]
""")


# 1.2 OneHotEncoder

## 📖 Definition
Creates binary columns for each category. Each column indicates presence (1) or absence (0) of that category.

## 🎯 When to Use
• Nominal data (no natural order)
• Features (X) for linear models (Logistic Regression, SVM, Neural Networks)

## Visual Representation

Original:    Color
            ┌─────┐
            │ Red │
            │ Blue│
            │Green│
            └─────┘

OneHotEncode ↓

        Red  Blue  Green
        ┌────┬─────┬─────┐
        │ 1  │ 0   │ 0   │  (Red)
        │ 0  │ 1   │ 0   │  (Blue)
        │ 0  │ 0   │ 1   │  (Green)
        └────┴─────┴─────┘

## 🔄 Workflow Diagram

┌──────────────────┐
│ Original Data    │  ['Red', 'Blue', 'Green', 'Blue']
└────────┬─────────┘
         ↓
┌──────────────────┐
│ Identify Unique  │  Categories: Red, Blue, Green
│ Categories       │  (n = 3 categories)
└────────┬─────────┘
         ↓
┌──────────────────┐
│ Create Binary    │  Create 3 new columns
│ Columns          │  [is_Red, is_B

In [ ]:
from sklearn.preprocessing import OneHotEncoder  # Import the encoder class
import pandas as pd  # For DataFrame operations

# Create sample nominal data (colors have no inherent order)
colors = pd.DataFrame({'Color': ['Red', 'Blue', 'Green', 'Blue', 'Red']})

# Initialize OneHotEncoder
ohe = OneHotEncoder(
    sparse_output=False,       # use sparse_output in newer scikit-learn versions
    handle_unknown='ignore'    # If new category appears later, set all columns to 0
)

# fit_transform does two things:
# 1. fit() - Learns unique categories: ['Blue', 'Green', 'Red']
# 2. transform() - Converts each value to binary vector
colors_encoded = ohe.fit_transform(colors[['Color']])  
# Note: Double brackets [[ ]] keep it as DataFrame. Single bracket would be Series.

# Create readable DataFrame with column names
colors_df = pd.DataFrame(
    colors_encoded, 
    columns=[f'Color_{c}' for c in ohe.categories_[0]]  # categories_[0] = ['Blue','Green','Red']
)

print("Original:\n", colors)
print("\nOneHot Encoded:\n", colors_df)

Original:
    Color
0    Red
1   Blue
2  Green
3   Blue
4    Red

OneHot Encoded:
    Color_Blue  Color_Green  Color_Red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         1.0          0.0        0.0
4         0.0          0.0        1.0


### 1.3 pd.get_dummies() (Pandas Method)

Pandas' built-in function for one-hot encoding. Creates dummy variables directly.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'City': ['NYC', 'LA', 'Chicago', 'NYC', 'LA'],
    'Price': [100, 200, 150, 120, 180]
})

# One-liner encoding
encoded_df = pd.get_dummies(df, columns=['City'], prefix='City')

print(encoded_df)

# Output:
#    Price  City_Chicago  City_LA  City_NYC
# 0    100             0        0         1
# 1    200             0        1         0
# 2    150             1        0         0
# 3    120             0        0         1
# 4    180             0        1         0

   Price  City_Chicago  City_LA  City_NYC
0    100         False    False      True
1    200         False     True     False
2    150          True    False     False
3    120         False    False      True
4    180         False     True     False


Original Data: 10 rows of 'Red', 'Blue', 'Green'

LabelEncoder:
Column: [2, 0, 1, 2, 0, 1, 2, 0, 1, 2]
Memory: 10 integers (~80 bytes)

OneHotEncoder:
Columns: [1,0,0]  [0,1,0]  [0,0,1]  ...
         [0,1,0]  [1,0,0]  [0,0,1]  ...
Memory: 10 × 3 = 30 floats (~240 bytes)